name: 'Dispatch Workflow'
description: 'Dispara o workflow já existente na branch temporária.'
inputs:
  workflow-file:
    description: 'Nome do arquivo workflow na raiz de workflows'
    required: true
  branch:
    description: 'Nome da branch temporária'
    required: true
  inputs-json:
    description: 'Inputs para o workflow (JSON)'
    required: true
  token:
    description: 'GitHub Token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
